### ISSUE TITLE
Bluetooth disappears after one or more system suspend

### ISSUE THREAD

**Issue by samadadi** [elementary/wingpanel-indicator-bluetooth#103]
I have this problem from the start of using elementary os & recently I noticed that on every system suspend, bluetooth icon moves towards battery indicator icon and after one or more supsend It disappears completely. The bluetooth is on & works correctly. If you look at the screenshots that I took from my screen you see the difference in space, between bluetooth & battery icons.
![Screenshot from 2019-12-08 23-00-57](https://user-images.githubusercontent.com/18693428/70568199-b1d3e400-1bac-11ea-8947-82d9be911a3b.png)
![Screenshot from 2019-12-11 00-04-54](https://user-images.githubusercontent.com/18693428/70568219-b8faf200-1bac-11ea-84dc-c44db4d14e94.png)

**Comment by ryonakano** [comment]
Thank you for your report, but I guess this issue is essentially the same as #68.
