### ISSUE TITLE
Devices list frequently incorrect

### ISSUE THREAD

**Issue by peteruithoven** [elementary/wingpanel-indicator-bluetooth#111]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The list of devices in the bluetooth indicator is freqently incorrect. 
Comparison of list in indicator with settings for example:
![Screenshot from 2020-04-16 10-12-47@2x](https://user-images.githubusercontent.com/523210/79431753-255a8780-7fcb-11ea-8ca8-6f73812be826.png)
![Screenshot from 2020-04-16 18-39-03@2x](https://user-images.githubusercontent.com/523210/79482887-c2d8aa00-8011-11ea-832e-33fda4c18900.png)

### To Reproduce
~~I'm afraid this is unclear. It happens over time.~~
1. Have some paired bluetooth deviced. 
2. Open indicator
3. Execute both or eather one of these commands:
    - sudo modprobe -r btusb && sudo modprobe btusb
    - sudo service bluetooth restart
4. Reopen indicator

I think it would be interesting to compare the logic in the indicator vs the settings and see if there are mistakes in the indicator. 

### Expected behavior
The list of devices in the indicator is consistent with the list of devices in the bluetooth settings. 

### Actual behavior
The list of devices in the indicator contains lots of duplicates. 

~~Note that even when keeping the bluetooth settings open there are no duplicates there.~~
Note that something similar happens in the bluetooth settings when executing restarting the bluetooth serve (`sudo service bluetooth restart`).

## Platform Information
![Screenshot from 2020-04-16 10-18-05@2x](https://user-images.githubusercontent.com/523210/79432076-9b5eee80-7fcb-11ea-8d55-1169decfe78e.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
A first step was taken in this PR:
https://github.com/elementary/wingpanel-indicator-bluetooth/pull/17

**Comment by peteruithoven** [comment]
I think some issues arrise because I manually execute commands like:
- `sudo modprobe -r btusb && sudo modprobe btusb`
- `sudo service bluetooth restart`

Both of these, even individually seem to cause duplicates.  
I execute these semi frequently when I have bluetooth related issues.

**Comment by peteruithoven** [comment]
I added some logs in the [Manager](https://github.com/elementary/wingpanel-indicator-bluetooth/blob/master/src/Services/Manager.vala). Looks like the `on_interface_added` is called multiple times. It's called from the `object_added` and the `interface_added` handlers. 
We need both handlers to cover all cases, but how do we prevent duplicates? Should we keep a local list of known devices and don't call the signal when it already exists?

**Comment by peteruithoven** [comment]
Keeping a list of the known devices addresses and only calling the signal when it's unknown causes issues. The device status isn't properly updated in that case. 

Removing the existing device from the devices list seems to work. But only when I compared using the `address` instead of the `modalias`. (The `modalias` for both my Soundbuds Slim's was null)

**Comment by andirsun** [comment]
I still facing duplicate icon for my mouse. 
Im on 5.1.7
![Screenshot from 2020-11-04 16-02-05](https://user-images.githubusercontent.com/22928302/98167505-2d224080-1eb7-11eb-8b33-31b1d6a6c79d.png)

**Comment by peteruithoven** [comment]
@andirsun did you check this with the latest version from master or just what's now in elementary? Because I don't think this has been released yet:
https://github.com/elementary/wingpanel-indicator-bluetooth/compare/2.1.5...master

**Comment by astaszek** [comment]
I'm experiencing kinda the same problem after having my mouse paired to another laptop.

To reproduce :
1. Pair a BT mouse to eOS
2. Pair the mouse to another OS
3. Pair the mouse back to eOS

Expected behaviour : 
No unpaired devices in the wingpanel window, delete all previous entries related to the re-paired BT device.

Actual behaviour : 
Few old entries in the wingpanel window, few old entries in unpaired devices (which can't be even connected to, so I have to look which one is the good one).

![image](https://user-images.githubusercontent.com/74073424/111608988-1d5a2780-87da-11eb-8460-dd3fa44f05b9.png)
