### ISSUE TITLE
Conflict paired device

### ISSUE THREAD

**Issue by Edix96** [elementary/wingpanel-indicator-bluetooth#112]
There also a conflict with the device paired. (see the attachment)

Thanks a lot! 

![Screenshot from 2020-04-16 17-05-26](https://user-images.githubusercontent.com/26300784/79479383-966a6100-8004-11ea-89b3-0ced2d1048bf.png)

**Comment by peteruithoven** [comment]
What do you mean with "conflict"? 
I see duplicate items maybe? 

If the list is incorrect I opened an issue on that yesterday: #111

**Comment by Edix96** [comment]
Yes! That's it!
Thanks
