### ISSUE TITLE
Bluetooth automatically turns on after waking up the laptop from sleep

### ISSUE THREAD

**Issue by shubhamthedev** [elementary/wingpanel-indicator-bluetooth#117]
Even after turning off the Bluetooth in System settings the Bluetooth turns on automatically after waking up the system from sleep.

**Comment by vjr** [comment]
Can you check if https://github.com/elementary/wingpanel-indicator-bluetooth/pull/143 fixes this issue?

**Comment by BugFixesAndPerformanceImprovements** [comment]
Still happens in elementaryOS 7.0.
