### ISSUE TITLE
Impossibile delete bluetooth-devices

### ISSUE THREAD

**Issue by ITSRizz** [elementary/wingpanel-indicator-bluetooth#118]
Unable to delete Bluetooth devices from the Bluetooth section.

**Comment by danrabbit** [comment]
Please adhere to the issue template in the future. 

Can you provide more steps to reproduce the issue? What did you try? Do you get any error output? Etc

**Comment by ITSRizz** [comment]
I solved it myself, I close the problem, it was my mistake. 
Thanks anyway for the support :-)
