### ISSUE TITLE
Wireless earphone disappears after suspend

### ISSUE THREAD

**Issue by zshanabek** [elementary/wingpanel-indicator-bluetooth#121]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

After suspend I don't see available devices in Bluetooth wingpanel. However the bluetooth on my wireless earphone is turned on

### To Reproduce
1. Suspend laptop
2. Turn it on 
3. Click on Bluetooth indicator in wingpanel
4. There are no available devices

### Expected behavior
I expected to see there my phone and wireless headset
### Screenshot

![image](https://user-images.githubusercontent.com/24398089/87536992-c1c02300-c6bb-11ea-9df2-736d00b708d8.png)

## Platform Information

Wireless earphone: JBL Tune115BT

Laptop: Lenovo G50-70

![image](https://user-images.githubusercontent.com/24398089/87538321-d8677980-c6bd-11ea-8aae-ba30da89ed68.png)

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by andirsun** [comment]
This is not happening for me in elementary 5.1.7 or 6.0.

**Comment by zshanabek** [comment]
> This is not happening for me in elementary 5.1.7 or 6.0.

And it doesn't mean that this bug is not gonna happen in other devices
