### ISSUE TITLE
Devices missing left padding with new stylesheet

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-bluetooth#126]
So this might be a stylesheet issue, but I've only noticed it here so far. When using this indicator in the greenfield stylesheet, it looks like we're missing the side padding for devices. It looks correct under the old stylesheet.

# Hera stylesheet

![Screenshot from 2020-08-31 14-39-40](https://user-images.githubusercontent.com/611168/91766549-f9b1f580-eb97-11ea-80d2-2f836f7d7e55.png)

# Odin stylesheet

![Screenshot from 2020-08-31 14-39-52](https://user-images.githubusercontent.com/611168/91766570-03d3f400-eb98-11ea-9d10-2bce8f429426.png)

**Comment by andirsun** [comment]
This is not happening right now. Maybe you want to close the issue .

**Comment by danrabbit** [comment]
Ah yeah I fixed this. It was related to images in menu menuitems and not popover menuitems :)
