### ISSUE TITLE
Bluetooth can't find any device

### ISSUE THREAD

**Issue by adrianptr** [elementary/wingpanel-indicator-bluetooth#127]
Bluetooth can't find any device

Notebook: HP 250 G3
OS: Elementary OS 5.1.7 Hera
CPU: Intel Celeron N2840

**Comment by cassidyjames** [comment]
@adrianptr the indicator just shows currently- or previously-paired devices but doesn't do discovery afaik. Can you be more specific regarding the issue you're having, what you've tried, etc.? As is there's not enough information for us to address anything here.

**Comment by adrianptr** [comment]
I'm looking for new devices, it finds nothing. On a desktop computer with the same system, but with a bluetooth stylus, it works correctly. Tomorrow I will try to install third party drivers.

**Comment by cassidyjames** [comment]
@adrianptr where are you looking for new devices? From System Settings → Bluetooth, or from the Bluetooth indicator in the top panel?

**Comment by adrianptr** [comment]
Yes, is right section? If isn't, I'm sorry for my mistake.

**Comment by Timetry** [comment]
可能你的蓝牙设备没有上电造成的，可以尝试在终端执行以下命令：
rfkill unblock bluetooth hciconfig hci0 up

**Comment by adrianptr** [comment]
I resolved the problem installing third party drivers. I'm sorry for trouble. You can close the thread.
