### ISSUE TITLE
Bluetooth icon in the panel blinks when toggling capslock (EOS 6 beta)

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/wingpanel-indicator-bluetooth#154]
## What Happened
The Bluetooth indicator blinks when toggling the capslock button. It happens only when capslock icon is shown in the panel. I don't know about the numlock since I don't have it.

## Expected Behavior
Bluetooth indicator should mind its own business. lol

## Steps to Reproduce
Toggle capslock on and off while watch the bluetooth indicator

https://user-images.githubusercontent.com/49320606/119238118-a1989600-bb0e-11eb-8a03-20d9ae78f37a.mp4

**Comment by davidmhewitt** [comment]
I imagine this is a duplicate of https://github.com/elementary/wingpanel/issues/106 ?

**Comment by KarkanAlzwayed** [comment]
@davidmhewitt I'm not sure, but I know it's driving me crazy. Lol

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/wingpanel/pull/486.
