### ISSUE TITLE
newly included screenshot is erroneously installed to /usr/lib*/wingpanel

### ISSUE THREAD

**Issue by decathorpe** [elementary/wingpanel-indicator-bluetooth#19]
The CMake files need to be adapted, because right now, everything in data/* is installed indiscriminately by glob:

```cmake
# Files
file (GLOB resources "${CMAKE_CURRENT_SOURCE_DIR}/data/*")
install (FILES ${resources} DESTINATION ${PKGDATADIR})
```

Since the new screenshot is the only "resource" in this case, those 3 lines can just be dropped, I think.

**Comment by bil-elmoussaoui** [comment]
@tintou this can be closed :)

**Comment by tintou** [comment]
indeed
