### ISSUE TITLE
Vertically center the icons

### ISSUE THREAD

**Issue by bilelmoussaoui** [elementary/wingpanel-indicator-bluetooth#21]
The icon of the linked device isn't centered vertically, and as  the icons doesn't have all the same shape/size it looks quite ugly especially when you hover it...
![wingpanel](https://cloud.githubusercontent.com/assets/7660997/26223126/0fb056f2-3c1d-11e7-85cf-bdd443eb5a22.png)

**Comment by danrabbit** [comment]
This is a problem with the icon set. Closing here and opening here: https://github.com/elementary/icons/issues/471
