### ISSUE TITLE
Set A2DP as default mode for Bluetooth audio

### ISSUE THREAD

**Issue by Maccer1** [elementary/wingpanel-indicator-bluetooth#22]
When you connect a BT headset it usually connects first to HSP/HFP mode and then you have to switch to A2DP mode. To make A2DP work you need to do a lot of juggling (disconnecting, reconecting switching profiles...), so why don't just set A2DP as default?

I don't know if many people uses HSP but it sounds so bad so I don't think many people would want to use it. That's why I think this could be a good idea.

A more extreme idea would be removing HSP/HFP  but I don't think you would like that idea.. I wouldn't mind if you remove it, though ;)

**Comment by danrabbit** [comment]
This is an upstream issue that is being worked on in PulseAudio. Marking as "Invalid" for this tracker
