### ISSUE TITLE
Colapsed window shows no devices

### ISSUE THREAD

**Issue by saitam1** [elementary/wingpanel-indicator-bluetooth#34]
This is what the window looks like after clicking the bluetooth icon and then "Discover Devices...", no devices are shown, because the window is too small and it seems as there are no devices.

![b1](https://user-images.githubusercontent.com/23245678/34435612-560c478c-ec8f-11e7-8d01-8970eec2c2ec.png)

After stretching the window it looks like this:

![b2](https://user-images.githubusercontent.com/23245678/34435632-7b61082e-ec8f-11e7-8e08-deacca0226bf.png)

Initiating the window with another size would solve this problem.

**Comment by danrabbit** [comment]
Closing since we no longer use GNOME bluetooth wizard. This is fixed in switchboard-plug-bluetooth master
