### ISSUE TITLE
Reconsider "Bluetooth Settings…" label

### ISSUE THREAD

**Issue by danirabbit** [elementary/wingpanel-indicator-bluetooth#42]
It would break convention, but it might be a bit more discoverable and accurate to name this label something like "Manage Devices…"

**Comment by cassidyjames** [comment]
Hmmm. I think I'm okay with more semantic labels, as long as we are consistent. I don't think "Bluetooth Settings…" is particularly unclear or inaccurate, though.

**Comment by danrabbit** [comment]
I wish I had left a little more context here. I'm guessing this was in response to something a user said somewhere?

**Comment by danirabbit** [comment]
Gonna close this since it would break convention
