### ISSUE TITLE
Gsettings key to hide the indicator

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel-indicator-bluetooth#59]
In order to solve https://github.com/elementary/switchboard-plug-bluetooth/issues/42 we'd need to add a settings key here in the indicator

Alternatively I suppose we could do this from the wingpanel side and create a way to hide any arbitrary indicator. Thoughts?

**Comment by parnold-x** [comment]
I have done a blacklist feature back then. https://github.com/elementary/wingpanel/blob/master/lib/IndicatorManager.vala#L99

**Comment by uncertainquark** [comment]
Is there an update on this? For now, I have disabled bluetooth from BIOS because the OS keeps on turning it ON every session log in. And it is both kinda annoying and not required since I don't use bluetooth at all.

**Comment by danrabbit** [comment]
I'm going to close this for the bluetooth indicator as "Out of Scope" since I think if we want to implement hiding and showing indicators, we want to do it from the panel side

**Comment by uncertainquark** [comment]
So, is there some other repo where this bug should be reopened/filed?

**Comment by donadigo** [comment]
@uncertainquark it's either wingpanel or switchboard since both components will have to be touched here.
I have already filled an issue for wingpanel here: https://github.com/elementary/wingpanel/issues/213.
