### ISSUE TITLE
Markup not applied on paired device label

### ISSUE THREAD

**Issue by dimsk** [elementary/wingpanel-indicator-bluetooth#69]
Latest eOS 5.0 renders tags instead of bold text.

![bildschirmfoto von 2019-01-24 21-24-04](https://user-images.githubusercontent.com/5050706/51706975-50e8ff00-2020-11e9-816d-f18874747bb9.png)

**Comment by peteruithoven** [comment]
I don't have the issue with my devices:
![screenshot from 2019-01-24 21 59 39](https://user-images.githubusercontent.com/523210/51708176-7e837780-2023-11e9-81d1-60215f8ed8a6.png)

Looks like Gtk.label markup get's confused by the `&`. I can reproduce the issue when I manually add it:
```
        name_label = new Gtk.Label ("<b>%s</b>".printf ("Something & something"));
        name_label.halign = Gtk.Align.START;
        name_label.valign = Gtk.Align.END;
        name_label.vexpand = true;
        name_label.use_markup = true;
```
