### ISSUE TITLE
Device order is random?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/wingpanel-indicator-bluetooth#74]
It looks like the device order is random:
![montage](https://user-images.githubusercontent.com/523210/52521916-00f47400-2c7f-11e9-833e-40426ad45c57.png)

Maybe we could order them alphabetically?

**Comment by danrabbit** [comment]
Yeah it looks like it's just a Gtk.Box instead of a listbox that we could add a sort function to: https://github.com/elementary/wingpanel-indicator-bluetooth/blob/master/src/Widgets/PopoverWidget.vala#L32
