### ISSUE TITLE
BT indicator is blurry on new greeter (it was on old one too) @4K and scaling x2

### ISSUE THREAD

**Issue by DanyGee** [elementary/wingpanel-indicator-bluetooth#92]
The bluetooth (and only this one) indicator is still blurry in new greeter @ 4K and scaling x2.
Once I switch off the BT it becomes crisp and stays like that till next reboot when, again, per default it is blurry.

My system:
![Screenshot from 2019-09-01 09 06 04@2x](https://user-images.githubusercontent.com/26818551/65643759-dd562200-dff2-11e9-9aed-c4e98d249c94.png)

**Comment by DanyGee** [comment]
Half a year passed and no fix :clock1:

**Comment by lenemter** [comment]
I cannot reproduce it. Probably fixed in https://github.com/elementary/wingpanel-indicator-bluetooth/pull/196
